#!/bin/bash

export AWS_ACCESS_KEY_ID=[YOUR AWS ACCESS KEY ID]
export AWS_SECRET_ACCESS_KEY=[YOUR AWS SECRET ACCESS KEY]
export S3_BUCKET=[YOUR S3 BUCKET]
export CLOUDFRONT_RTMP_DOMAIN=[YOUR CLOUDFRONT RTMP DOMAIN]
export CLOUDFRONT_WEB_DOMAIN=[YOUR CLOUDFRONT WEB DOMAIN]
export CLOUDFRONT_KEYPAIR_ID=[YOUR CLOUDFRONT KEYPAIR ID]
export TRANSCODER_PIPELINE_ID=[YOUR TRANSCODER PIPELINE ID]
export BASICAUTH_GUEST_USERNAME=[BASICAUTH USERNAME FOR GUEST]
export BASICAUTH_GUEST_PASSWORD=[BASICAUTH PASSWORD FOR GUEST]
export BASICAUTH_ADMIN_USERNAME=[BASICAUTH USERNAME FOR ADMIN]
export BASICAUTH_ADMIN_PASSWORD=[BASICAUTH PASSWORD FOR ADMIN]

